[project]
name = "mtg-rdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rdflib>=7.4.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
